标量 向量 矩阵 张量
这是一个很好的问题。向量、矩阵和张量是数学和深度学习中的基本概念。让我们逐一解释这些概念，并说明它们之间的关系：

1. 向量（Vector）:
   - 定义：一个有序的数字列表，可以表示方向和大小。
   - 维度：一维数组。
   - 表示：通常用粗体小写字母表示，如 v。
   - 例子：v = [1, 2, 3] 或 v = (1, 2, 3)
   - 在深度学习中：可以表示一个样本的特征或一层神经网络的激活值。

2. 矩阵（Matrix）:
   - 定义：二维数字数组，由行和列组成。
   - 维度：二维。
   - 表示：通常用大写字母表示，如 A。
   - 例子：A = [[1, 2], [3, 4], [5, 6]]（3行2列的矩阵）
   - 在深度学习中：可以表示多个样本的特征集合，或神经网络的权重。

3. 张量（Tensor）:
   - 定义：n维数组，是向量和矩阵的泛化。
   - 维度：可以是任意维度（0维、1维、2维、3维或更高维）。
   - 表示：通常用大写斜体字母表示，如 T。
   - 例子：
     - 0维张量（标量）：42
     - 1维张量（向量）：[1, 2, 3]
     - 2维张量（矩阵）：[[1, 2], [3, 4]]
     - 3维张量：[[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
   - 在深度学习中：广泛用于表示和处理多维数据，如图像、视频序列等。

4. 概念之间的关系：
   - 标量（0维张量）< 向量（1维张量）< 矩阵（2维张量）< 高维张量
   - 每个概念都是下一个概念的特例：
     - 标量是只有一个元素的向量
     - 向量是只有一列（或一行）的矩阵
     - 矩阵是二维张量

5. 在深度学习中的应用：
   - 向量：表示单个样本或特征。
   - 矩阵：表示批量数据或网络层的权重。
   - 张量：表示批量的多维数据（如图像批次）或复杂的网络结构。

6. 操作：
   - 向量：点积、叉积、范数等。
   - 矩阵：加法、乘法、转置、求逆等。
   - 张量：张量积、收缩、卷积等。

7. 在编程中的表示：
   - Python中，通常使用NumPy或PyTorch等库来处理这些数据结构。
   - 例如，在NumPy中：
     ```python
     import numpy as np
     
     vector = np.array([1, 2, 3])
     matrix = np.array([[1, 2], [3, 4]])
     tensor = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
     ```

8. 维度（Dimension）vs 秩（Rank）：
   - 在讨论张量时，维度和秩经常互换使用。
   - 张量的秩指的是它的维度数量，而不是矩阵理论中的秩概念。

理解这些概念对于深入学习深度学习和机器学习算法至关重要，因为大多数操作和数据处理都基于这些数学结构。

您对这些概念在特定深度学习任务中的应用还有什么疑问吗？或者您想了解如何在实际编程中操作这些数据结构？

In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3])
y = np.array([4,5,6])
x.__class__

numpy.ndarray

In [3]:
x.ndim

1

In [4]:
x.shape

(3,)

In [5]:
z = x*y
print(z)

[ 4 10 18]


In [6]:
z.shape


(3,)

In [7]:
x1 = np.array([[1,2,3],[4,5,6]])
x1.shape

(2, 3)

In [8]:
x2 = np.array([[5,6,7],[6,7,8]])

In [9]:
x2-x1

array([[4, 4, 4],
       [2, 2, 2]])

In [10]:
x2+x1

array([[ 6,  8, 10],
       [10, 12, 14]])

In [11]:
x1*10

array([[10, 20, 30],
       [40, 50, 60]])

In [12]:
x3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [13]:
x3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [14]:
x1+x3

array([[[ 2,  4,  6],
        [ 8, 10, 12]],

       [[ 8, 10, 12],
        [14, 16, 18]]])

In [15]:
x1 = np.random.randn(3,3)
x1

array([[-0.53643933,  2.53810123, -1.32659342],
       [ 0.19940747, -0.97841915, -0.76656323],
       [ 0.91503703,  0.81502956, -1.28903293]])

In [16]:
x1 = np.random.rand(3,3,3)
x1

array([[[0.01971744, 0.97937697, 0.15217466],
        [0.83536361, 0.99225306, 0.97872501],
        [0.5036121 , 0.00425232, 0.12810977]],

       [[0.45497361, 0.82807094, 0.88701847],
        [0.09146157, 0.05615298, 0.61082225],
        [0.80352193, 0.51471489, 0.52759206]],

       [[0.13311632, 0.88392714, 0.93387844],
        [0.93395025, 0.40138094, 0.60037206],
        [0.8205762 , 0.6532737 , 0.67028799]]])

In [17]:
x1.shape

(3, 3, 3)

In [18]:
x1 = x1.reshape(9,3)
x1

array([[0.01971744, 0.97937697, 0.15217466],
       [0.83536361, 0.99225306, 0.97872501],
       [0.5036121 , 0.00425232, 0.12810977],
       [0.45497361, 0.82807094, 0.88701847],
       [0.09146157, 0.05615298, 0.61082225],
       [0.80352193, 0.51471489, 0.52759206],
       [0.13311632, 0.88392714, 0.93387844],
       [0.93395025, 0.40138094, 0.60037206],
       [0.8205762 , 0.6532737 , 0.67028799]])

In [19]:
x1.shape

(9, 3)

In [20]:
import numpy as np

# 创建示例张量
tensor_3d = np.random.rand(2, 3, 4)  # 3维张量
tensor_4d = np.random.rand(5, 2, 3, 4)  # 4维张量

# 方法1：利用 NumPy 的自动广播（如果形状兼容）
result_1 = tensor_4d + tensor_3d  # 自动广播 3d 到 (5, 2, 3, 4)

# 方法2：手动调整 3d 张量的形状
tensor_3d_reshaped = tensor_3d.reshape(1, 2, 3, 4)
print(tensor_3d_reshaped)
result_2 = tensor_4d + tensor_3d_reshaped

# 方法3：使用 expand_dims 添加新维度
tensor_3d_expanded = np.expand_dims(tensor_3d, axis=0)
result_3 = tensor_4d + tensor_3d_expanded

# 方法4：使用 tile 手动广播
tensor_3d_tiled = np.tile(tensor_3d, (5, 1, 1, 1))
result_4 = tensor_4d + tensor_3d_tiled

# 方法5：使用 broadcast_to
tensor_3d_broadcasted = np.broadcast_to(tensor_3d, (5, 2, 3, 4))
result_5 = tensor_4d + tensor_3d_broadcasted

# 验证所有结果相同
print(np.allclose(result_1, result_2))
print(np.allclose(result_1, result_3))
print(np.allclose(result_1, result_4))
print(np.allclose(result_1, result_5))

[[[[0.04062897 0.2033863  0.67787829 0.31990158]
   [0.94040427 0.03008706 0.01573785 0.8291351 ]
   [0.09834183 0.31579578 0.02161889 0.71702287]]

  [[0.00469381 0.81399864 0.29640079 0.27090117]
   [0.18841948 0.64605599 0.07870182 0.06038581]
   [0.63235758 0.69957654 0.78885197 0.59189855]]]]
True
True
True
True


In [21]:
x1 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
x1.shape

(2, 2, 3)

In [22]:
x1.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

机器学习，神经网络，深度学习，大模型

神经网络：
1. 输入层：接收原始数据作为输入。
2. 隐藏层：包含多个神经元，每个神经元接收来自前一层的输出，并产生一个输出。
3. 输出层：接收来自隐藏层的输出，并产生最终的预测结果。
4. 激活函数：在每个神经元中，通过非线性函数将输入转换为输出。
5. 损失函数：用于衡量模型预测结果与真实结果之间的差异。
6. 优化器：用于调整模型的参数，以最小化损失函数。
7. 训练过程：通过反向传播算法，根据梯度下降法，更新模型的参数，

In [34]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

x = np.random.randn(1,2)
x

array([[0.85221781, 1.48102798]])

In [35]:
W1 = np.random.randn(2,4)
W1

array([[-1.23505733,  0.476996  ,  0.17119268,  0.18139408],
       [-0.15379984,  0.12913964,  0.56848353,  0.01231592]])

In [36]:
b1 = np.random.randn(4)
b1

array([ 0.68111216,  0.58927668, -2.011461  , -0.18847236])

In [26]:
h = np.dot(x,W1)+b1
h

array([[-4.06369803e-03, -6.62780250e+00,  5.52578484e+00,
         5.15851254e-01],
       [-1.20281128e+00, -1.72757472e+00,  1.12334435e+00,
         1.13587680e-01],
       [-1.43212706e+00, -2.25084489e+00,  1.70204646e+00,
        -6.29096560e-02],
       [-1.07422011e-01, -2.08087577e+00,  1.13413973e+00,
         7.62250925e-01],
       [-2.43948138e-01, -1.84356718e+00,  9.44785416e-01,
         6.94575269e-01],
       [-7.67298649e-01,  2.82788621e-01, -9.64599790e-01,
         5.18069260e-01],
       [-5.41384838e-01,  1.07415632e+00, -1.80306182e+00,
         7.10748383e-01],
       [-1.11939797e+00,  3.42412957e+00, -3.91336090e+00,
         5.15910705e-01],
       [-4.59842954e-01, -4.20729862e-01, -3.73680754e-01,
         6.58949820e-01],
       [-4.72631705e-01,  9.40916486e-03, -7.88215109e-01,
         6.80409951e-01]])

In [27]:
h.shape


(10, 4)

In [28]:
h.ndim

2

In [29]:
a = sigmoid(h)
a

array([[0.49898408, 0.00132132, 0.99603306, 0.62617714],
       [0.23097548, 0.15089806, 0.75460853, 0.52836643],
       [0.19276748, 0.09527661, 0.84580183, 0.48427777],
       [0.47317029, 0.11096954, 0.75660206, 0.68184223],
       [0.43931362, 0.13662995, 0.72006527, 0.66698394],
       [0.31706375, 0.57022976, 0.27595819, 0.62669618],
       [0.36786549, 0.74538653, 0.14147876, 0.6705665 ],
       [0.24612297, 0.96845019, 0.01958214, 0.62619106],
       [0.38702308, 0.39634211, 0.40765192, 0.65902444],
       [0.38399354, 0.50235227, 0.31255205, 0.66383019]])

In [30]:
W2 = np.random.randn(4,3)
b2 = np.random.randn(3)
s = np.dot(a,W2)+b2

In [31]:
s.shape

(10, 3)

In [32]:
s.ndim

2

In [33]:
s

array([[-0.58525983,  1.77211756, -1.1210119 ],
       [-1.07626382,  1.60346155, -1.14634126],
       [-1.15398071,  1.48357421, -1.10096496],
       [-0.60214591,  1.92500366, -1.19828605],
       [-0.66877223,  1.90273343, -1.20247674],
       [-0.96952546,  2.02837485, -1.37122057],
       [-0.88942595,  2.21505035, -1.47178055],
       [-1.11808632,  2.22165643, -1.56280745],
       [-0.81488233,  2.01276836, -1.30693758],
       [-0.83587017,  2.07724885, -1.35593391]])