标量 向量 矩阵 张量
这是一个很好的问题。向量、矩阵和张量是数学和深度学习中的基本概念。让我们逐一解释这些概念，并说明它们之间的关系：

1. 向量（Vector）:
   - 定义：一个有序的数字列表，可以表示方向和大小。
   - 维度：一维数组。
   - 表示：通常用粗体小写字母表示，如 v。
   - 例子：v = [1, 2, 3] 或 v = (1, 2, 3)
   - 在深度学习中：可以表示一个样本的特征或一层神经网络的激活值。

2. 矩阵（Matrix）:
   - 定义：二维数字数组，由行和列组成。
   - 维度：二维。
   - 表示：通常用大写字母表示，如 A。
   - 例子：A = [[1, 2], [3, 4], [5, 6]]（3行2列的矩阵）
   - 在深度学习中：可以表示多个样本的特征集合，或神经网络的权重。

3. 张量（Tensor）:
   - 定义：n维数组，是向量和矩阵的泛化。
   - 维度：可以是任意维度（0维、1维、2维、3维或更高维）。
   - 表示：通常用大写斜体字母表示，如 T。
   - 例子：
     - 0维张量（标量）：42
     - 1维张量（向量）：[1, 2, 3]
     - 2维张量（矩阵）：[[1, 2], [3, 4]]
     - 3维张量：[[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
   - 在深度学习中：广泛用于表示和处理多维数据，如图像、视频序列等。

4. 概念之间的关系：
   - 标量（0维张量）< 向量（1维张量）< 矩阵（2维张量）< 高维张量
   - 每个概念都是下一个概念的特例：
     - 标量是只有一个元素的向量
     - 向量是只有一列（或一行）的矩阵
     - 矩阵是二维张量

5. 在深度学习中的应用：
   - 向量：表示单个样本或特征。
   - 矩阵：表示批量数据或网络层的权重。
   - 张量：表示批量的多维数据（如图像批次）或复杂的网络结构。

6. 操作：
   - 向量：点积、叉积、范数等。
   - 矩阵：加法、乘法、转置、求逆等。
   - 张量：张量积、收缩、卷积等。

7. 在编程中的表示：
   - Python中，通常使用NumPy或PyTorch等库来处理这些数据结构。
   - 例如，在NumPy中：
     ```python
     import numpy as np
     
     vector = np.array([1, 2, 3])
     matrix = np.array([[1, 2], [3, 4]])
     tensor = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
     ```

8. 维度（Dimension）vs 秩（Rank）：
   - 在讨论张量时，维度和秩经常互换使用。
   - 张量的秩指的是它的维度数量，而不是矩阵理论中的秩概念。

理解这些概念对于深入学习深度学习和机器学习算法至关重要，因为大多数操作和数据处理都基于这些数学结构。

您对这些概念在特定深度学习任务中的应用还有什么疑问吗？或者您想了解如何在实际编程中操作这些数据结构？

In [18]:
import numpy as np

In [19]:
x = np.array([1,2,3])
y = np.array([4,5,6])
x.__class__

numpy.ndarray

In [20]:
x.ndim

1

In [21]:
x.shape

(3,)

In [22]:
z = x*y
print(z)

[ 4 10 18]


In [23]:
z.shape


(3,)

In [24]:
x1 = np.array([[1,2,3],[4,5,6]])
x1.shape

(2, 3)

In [25]:
x2 = np.array([[5,6,7],[6,7,8]])

In [30]:
x2-x1

array([[4, 4, 4],
       [2, 2, 2]])

In [29]:
x2+x1

array([[ 6,  8, 10],
       [10, 12, 14]])

In [31]:
x1*10

array([[10, 20, 30],
       [40, 50, 60]])

In [32]:
x3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [33]:
x3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [34]:
x1+x3

array([[[ 2,  4,  6],
        [ 8, 10, 12]],

       [[ 8, 10, 12],
        [14, 16, 18]]])

In [37]:
x1 = np.random.randn(3,3)
x1

array([[ 1.44523697,  0.25761555, -1.73597918],
       [-0.51964313,  1.74973614,  0.13126249],
       [ 0.07507427,  0.70614692, -1.02991708]])

In [38]:
x1 = np.random.rand(3,3)
x1

array([[0.33453484, 0.67193243, 0.48164376],
       [0.48604211, 0.05615452, 0.75111036],
       [0.12467161, 0.75719624, 0.01837952]])

In [45]:
x1 = np.random.rand(3,3,3)
x1

array([[[0.82249613, 0.47074168, 0.39242121],
        [0.36037   , 0.08939851, 0.03349804],
        [0.68610729, 0.77890884, 0.09551061]],

       [[0.10576627, 0.12060874, 0.38554214],
        [0.41262808, 0.84898859, 0.27549294],
        [0.70334723, 0.52945376, 0.17683204]],

       [[0.85524478, 0.3288257 , 0.28165967],
        [0.14126962, 0.81641693, 0.93888589],
        [0.50468293, 0.01811155, 0.27253098]]])

In [47]:
x1.shape

(3, 3, 3)

In [52]:
x1 = x1.reshape(9,3)
x1

array([[0.82249613, 0.47074168, 0.39242121],
       [0.36037   , 0.08939851, 0.03349804],
       [0.68610729, 0.77890884, 0.09551061],
       [0.10576627, 0.12060874, 0.38554214],
       [0.41262808, 0.84898859, 0.27549294],
       [0.70334723, 0.52945376, 0.17683204],
       [0.85524478, 0.3288257 , 0.28165967],
       [0.14126962, 0.81641693, 0.93888589],
       [0.50468293, 0.01811155, 0.27253098]])

In [53]:
x1.shape

(9, 3)

In [60]:
import numpy as np

# 创建示例张量
tensor_3d = np.random.rand(2, 3, 4)  # 3维张量
tensor_4d = np.random.rand(5, 2, 3, 4)  # 4维张量

# 方法1：利用 NumPy 的自动广播（如果形状兼容）
result_1 = tensor_4d + tensor_3d  # 自动广播 3d 到 (5, 2, 3, 4)

# 方法2：手动调整 3d 张量的形状
tensor_3d_reshaped = tensor_3d.reshape(1, 2, 3, 4)
print(tensor_3d_reshaped)
result_2 = tensor_4d + tensor_3d_reshaped

# 方法3：使用 expand_dims 添加新维度
tensor_3d_expanded = np.expand_dims(tensor_3d, axis=0)
result_3 = tensor_4d + tensor_3d_expanded

# 方法4：使用 tile 手动广播
tensor_3d_tiled = np.tile(tensor_3d, (5, 1, 1, 1))
result_4 = tensor_4d + tensor_3d_tiled

# 方法5：使用 broadcast_to
tensor_3d_broadcasted = np.broadcast_to(tensor_3d, (5, 2, 3, 4))
result_5 = tensor_4d + tensor_3d_broadcasted

# 验证所有结果相同
print(np.allclose(result_1, result_2))
print(np.allclose(result_1, result_3))
print(np.allclose(result_1, result_4))
print(np.allclose(result_1, result_5))

[[[[0.51960391 0.1744725  0.2040778  0.5730581 ]
   [0.89438959 0.29528455 0.72875405 0.33049573]
   [0.70093614 0.94067729 0.57477334 0.80239207]]

  [[0.39333835 0.49587537 0.32727774 0.1759601 ]
   [0.41427796 0.66395095 0.06243747 0.61736204]
   [0.93068059 0.84137876 0.96863992 0.84909476]]]]
True
True
True
True
